%% Saving all period evaluation data into .mat

eval(strcat('alfaKalmanVMRMSEbyPeriod', 'K', num2str(selectCandidate), 'M', num2str(selectMeasurement), '=', 'alfaKalmanVMRMSEbyPeriod',';'))
eval(strcat('alfaCalVMRMSEbyPeriod', 'K', num2str(selectCandidate), 'M', num2str(selectMeasurement), '=', 'alfaCalVMRMSEbyPeriod',';'))

eval(strcat('save("data/Meritve/K',  num2str(selectCandidate),'/RMSEbyPeriodM', ...
    num2str(selectMeasurement), '.mat","','alfaKalmanVMRMSEbyPeriod', 'K', ...
    num2str(selectCandidate), 'M', num2str(selectMeasurement), '",','"alfaCalVMRMSEbyPeriod', 'K', ...
    num2str(selectCandidate), 'M', num2str(selectMeasurement),'");'))


eval(strcat('save("data/Meritve/K',  num2str(selectCandidate),'/RMSEbyPeriodM', ...
    num2str(selectMeasurement), '.mat","','alfaKalmanVMRMSEbyPeriod', 'K', ...
    num2str(selectCandidate), 'M', num2str(selectMeasurement), '",','"alfaCalVMRMSEbyPeriod', 'K', ...
    num2str(selectCandidate), 'M', num2str(selectMeasurement),'");'))

eval(strcat('save("data/Meritve/K',  num2str(selectCandidate),'/KneeCrankAngle', ...
    num2str(selectMeasurement), '.mat",','"kneeAngleVM",', ...
    '"phaseCM",','"phaseMax",','"ymin",','"ymax");'))
